### PR TITLE
port basic account creation to backend v2

### PR DESCRIPTION
**Pull request by wginsberg**
recreating PR #235 since I accidentally merged it

**Web frontend checklist**
- [x] Formatted my code with `make format`
- [x] There are no warnings from `make lint`
- [ ] There are no console warnings when running the app
- [ ] Added any new components to storybook
- [x] Added tests where relevant
- [x] All tests pass
- [x] Clicked around my changes running locally and it works
- [ ] Checked Desktop, Mobile and Tablet screen sizes

### CODE REVIEW

**Comment by wginsberg** [comment]
@darrenvong all comments should be addressed now, and I added the username field back since it doesn't make sense to leave it out here

**Comment by darrenvong** [comment]
> I added the username field back since it doesn't make sense to leave it out here

Does that mean with the new API, the user is created as soon as you filled in that first form? How does the rest of the signup flow map to the existing one? 🤔 Just wondering if the rest of the old UI/steps for sign up still make sense or if we need to re-work some of them

**Review by darrenvong — APPROVED** [review]
Anyway this looks good to me! Let's not block this so we have a first example for others to reference from 🎉  we can refine the details/my other questions later if something turns out to be off as you go through the sign up steps 😅

**Comment by wginsberg** [comment]
> > I added the username field back since it doesn't make sense to leave it out here
> 
> Does that mean with the new API, the user is created as soon as you filled in that first form? How does the rest of the signup flow map to the existing one? 🤔 Just wondering if the rest of the old UI/steps for sign up still make sense or if we need to re-work some of them

I sure hope so 😝 
We'll see what happens!

**Pull request merged**
