### PR TITLE
ci: use nextjs experimental 'outputStandalone' setting

### LINKED ISSUE #25: Unknown package mis-placed in devDependencies instead of dependencies in package.json
There is/was a bug in our package.json, specifically some package that is in devDependencies should be in dependencies.  This causes our code to not work properly when only the prod dependencies are installed which is ideally how we should run this in production.  However, the old Dockerfile installed the prod dependencies "over" the dev ones, such that both were always installed.  When we pivoted over to Kubernetes and cleaning everything up, we ran into this insane issue which took us a week to get to the bottom of specifically because there wasn't good/any logging or debug information telling us why it was crashing.  The NodeJS process would exit with exit code 137, which is an "OOM", but this had nothing to do with memory.  In checking metrics and in testing giving it tons of RAM it was still exiting with this code, and was giving no logs as to why it was failing.

The temporary fix is to use all the dev node_modules in production, making our docker image larger and our ability to scale/deploy a bit slower.  The "temporary" fix is shown below, which when the package.json is fixed can and should be reverted.

See: https://github.com/Couchers-org/web-frontend/pull/24/files

### PR DESCRIPTION
**Pull request by thdk**
Using this setting a 'standalone' folder is provided by next after a build cocntaining
just the required node modules and a server.js file.

To investigate wheter static and public folder should be on this runner image since nextjs docs
suggests these files should be served from cdn server.

fixes #25

**Backend checklist**
- [ ] Formatted my code by running `autoflake -r -i --remove-all-unused-imports src && isort . && black .` in `app/backend`
- [ ] Added tests for any new code or added a regression test if fixing a bug
- [ ] All tests pass
- [ ] Run the backend locally and it works
- [ ] Added migrations if there are any database changes, rebased onto `develop` if necessary for linear migration history

**Web frontend checklist**
- [ ] Formatted my code with `yarn format && yarn lint --fix`
- [ ] There are no warnings from `yarn lint`
- [ ] There are no console warnings when running the app
- [ ] Added any new components to storybook
- [ ] Added tests where relevant
- [ ] All tests pass
- [ ] Clicked around my changes running locally and it works
- [ ] Checked Desktop, Mobile and Tablet screen sizes

### CODE REVIEW

**Comment by lucaslcode** [comment]
This seems to work well, but I am going to install sharp as I see this error in the logs: `Error: 'sharp' is required to be installed in standalone mode for the image optimization to function correctly`

**Comment by lucaslcode** [comment]
Fixed above by installing `libc6-compat` in the Dockerfile

**Comment by thdk** [comment]
> ~~lgtm, Fixed above by installing `libc6-compat` in the Dockerfile~~
> I take it back, after loading the site the error re-appears. I still get `Error loading shared library libresolv.so.2: No such file or directory` when trying to run sharp directly.
> I will try reverting to node:slim 

Ah I shouldn't have touched the base image indeed!

**Comment by AndrewFarley** [comment]
Nice work @thdk / @lucaslcode, this seems to work, including...

- I confirm the final image size is now tiny (300MB)
- The build time is now very quick because of less installing of things (~2m)

I'd say, if we have an QA person/team maybe a deep dive on the dev deployed url: https://web-frontend-feature-next-output-standalone.couchers.dev can be done before we accept and merge this, since this is very different than our image up until this point that would be ideal.

**Review by darrenvong — APPROVED** [review]
I've given this some good old manual testing against the key functionalities like sending a message, host request, joining an events etc and they all seem to be working well!

**Review by lucaslcode — APPROVED** [review]
Sharp error is gone

**Pull request merged**
