### PR TITLE
Day(s) of week should appear on surf/host info

### PR DESCRIPTION
**Pull request by Krishnag09**
closes #1899- Day(s) of week should appear on surf/host info
--->

**Web frontend checklist**
- [x] Formatted my code with `make format`
- [x] There are no warnings from `make lint`
- [x] There are no console warnings when running the app
- [x] Added any new components to storybook
- [x] Added tests where relevant
- [x] All tests pass
- [x] Clicked around my changes running locally and it works
- [x] Checked Desktop, Mobile and Tablet screen sizes

### CODE REVIEW

**Comment by bakeiro** [comment]
Hi!, I don't find the issue 1899 😅

**Comment by Krishnag09** [comment]
> Hi!, I don't find the issue 1899 😅

https://github.com/Couchers-org/couchers/issues/1899

**Comment by bakeiro** [comment]
code looks good, I'll test it once I have time (if not you can send me please a pic of the result if looks good I think I can approve it )

**Comment by lucaslcode** [comment]
Please do not check the checklist if you have not actually done the items. This code would clearly break host request creation.

**Pull request closed without merging**
