### PR TITLE
grammar and text fixes for hosting preferences and about home

### LINKED ISSUE #116: Grammar & text errors under "hosting preferences" & "about my home"

### PR DESCRIPTION
**Pull request by Roshanjossey**
closes #116

made changes to translations files to address following points in the linked issue

> "Last minute requests" should be "Accepts last minute requests"

> "Accept camping" is grammatically incorrect and unclear. It should be "Tent camping available"

> "Accept children" & "accept pets" is grammatically incorrect and sounds strange. "Can host children" and "Can host guests with pets"

> "Accepts drinking" and "accepts smoking" also sounds strange. It should be "Okay with drinking" and "Okay with smoking"

> Also, the hashtag symbol # isn't universally understood as meaning "number", so it should say "Max number of hosts".

> Under "About my home" it is unclear that "Private / shared space" is referring to the room that the guest will be sleeping in. It should be changed to "Sleeping privacy". The options for hosts to choose should be changed from "shared" or "private" to "shared room" or "private room"

### Web frontend checklist

- [x] Formatted my code with `make format`
- [x] There are no warnings from `make lint`
- [ ] There are no console warnings when running the app
- [ ] Added any new components to storybook
- [ ] Added tests where relevant
- [ ] All tests pass
- [x] Clicked around my changes running locally and it works
- [x] Checked Desktop, Mobile and Tablet screen sizes

### Screenshots

image
image
image

### CODE REVIEW

**Review by aapeliv — DISMISSED** [review]
Great, thank you! Very glad to see this PR.

I agree that these changes make the UI better. The only small thing is that maybe something like "Hosts pets"/"Hosts children" is better, otherwise it makes it sound like it's a question of whether they *can* instead of if they *want to*, while the latter is a completely fine reason not to host pets/children.

That being said, feel free to merge or tweaks slightly and I can re-review.

**Comment by Roshanjossey** [comment]
Updated to `Hosts pets`, `Hosts children`

**Review by aapeliv — APPROVED** [review]
Great, thank you!!

**Comment by bakeiro** [comment]
@aapeliv @Roshanjossey merged ;)

**Pull request merged**
